- name: "Install node 13"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to switch to node v13.8.0
    sudo npm install -g n
    sudo n 13.8.0

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes